### ISSUE TITLE
AttributeError: 'Mongodb_retention_scheduler' object has no attribute 'hosts_fs

### ISSUE THREAD

**Issue by TomaszUrugOlszewski** [shinken-monitoring/mod-retention-mongodb#13]
Hi

As in subject. Today I rebooted server physcicaly (I have all components there). Sadly, every service is in PENDING state

In logs I can see this error message:

```
[1455692016] INFO: [receiver-master] I correctly loaded the modules: []
  File "/usr/local/lib/python2.7/dist-packages/shinken/scheduler.py", line 391, in hook_point
    f(self)
  File "/var/lib/shinken/modules/retention-mongodb/module.py", line 221, in hook_load_retention
    for h in self.hosts_fs.find():
AttributeError: 'Mongodb_retention_scheduler' object has no attribute 'hosts_fs'
```

**Comment by mohierf** [comment]
Which version of this module are you using? Your error is on line 221 but the corresponding code line in module.py is 221 ...

I suppose that you did `shinken install`? You should get the code from the repo because the module is not published with the last modifications ...

On my own, I forked this module and prepared a new version here: https://github.com/mohierf/mod-retention-mongodb. I am currently testing this version on my server and it seems really stable ...

**Comment by maethor** [comment]
Should be fixed in last version.
